### ISSUE TITLE
2G+ feature of CovPassCheck always shows "Negativer Schnelltest" although a negative PCR test was scanned

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-ios#125]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR & Huawei P Smart 2019
- OS version: iOS 15.3 & Android 10
- App version: 1.17

## Describe the bug

CovPassCheck always shows "Negativer Schnelltest when checking against 2G+ rules, even if a negative PCR test was scanned. 

## Steps to reproduce the issue

1. Create a test DCC for a negative PCR test
2. Scan it with the 3G feature of CovPassCheck
3. See that CovPassCheck correctly shows that it is a PCR test
4. Scan it with the 2G+ feature of CovPassCheck
5. See that CovPassCheck says it is a RAT

## Expected behaviour

The correct test should be shown. 

## Possible Fix

Probably somewhere the word "Schnelltest" is hardcoded.

## Additional context

This has hot fix potential IHMO because if there are 2G+ events which require a PCR test and now CovPassCheck shows the wrong test, this is really really bad.

**Comment by Ein-Tim** [comment]
@alexcimander Will you be able to look at this soon?

**Comment by Ein-Tim** [comment]
@timokoenig Do you have a guess why this issue happens?

Is the 1.17 code public already, btw?

**Comment by timokoenig** [comment]
@Ein-Tim it is not public yet therefore I was not able to look into the issue. Will do as soon as it will become available

**Comment by timokoenig** [comment]
@Ein-Tim can confirm this issue. Issue is here https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/756eca0448c92dceffa7a8c63a6dc9d8ad660883/Source/CovPassCheckApp/Source/Scenes/GProof/GProofViewModel.swift#L103 that always shows `Negative rapid test from %d hours ago`


@Kurt57 this might be a hotfix candidate

**Comment by Kurt57** [comment]
> @Ein-Tim can confirm this issue. Issue is here
> 
> https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/756eca0448c92dceffa7a8c63a6dc9d8ad660883/Source/CovPassCheckApp/Source/Scenes/GProof/GProofViewModel.swift#L103
> 
> that always shows `Negative rapid test from %d hours ago`
> @Kurt57 this might be a hotfix candidate

@timokoenig yes that seems like. I'm already confirming what has gone wrong there.

**Comment by Ein-Tim** [comment]
@Kurt57 

Will there be a hotfix?

**Comment by alexcimander** [comment]
Hey everyone! We are currently working on a fix. If we fix it with a hotfix or with the release 1.18 is now in discussion. We will keep you updated. Thank you everyone! 🚧

**Comment by Ein-Tim** [comment]
@alexcimander 

Nearly 2 weeks have passed since I reported this issue. What was done behind the scenes? Is a hot fix ready? Or will this be fixed in version 1.18?

**Comment by Ein-Tim** [comment]
@alexcimander 

Was this fixed with version 1.18? K can't verify the fix, sorry.

**Comment by timokoenig** [comment]
I would check but the source code is not available yet

**Comment by Ein-Tim** [comment]
@timokoenig 

Thanks!

**Comment by timokoenig** [comment]
I don't see a difference to the previous version, therefore not fixed.

**Comment by timokoenig** [comment]
Fixed with version 1.18

https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/1f1f5d283dfccc87efb8dadf8723c5f18721e449/Source/CovPassCheckApp/Source/Scenes/GProof/GProofViewModel.swift#L107

**Comment by Ein-Tim** [comment]
Thanks @timokoenig!
